version: "3"
services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - xpack.security.enabled=false
      volumes:
        - type: bind
          source: ./app/elastic
          target: /usr/share/elasticsearch/data
      ports:
          - "9200:9200"
  
  kibana:
    image: kibana:8.6.1
    ports:
      - '5601:5601'